# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BI_gZ_TdBcloXqoU9Zoijv-SoNuk8DBS
"""





openai.api_key = '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'

openai.Completion.create(
    engine="davinci",
    prompt="I miss you"
)
